id: P1244C545
initial_creation_type: ocr
source_metadata:
  volumes:
    c8051cbbb8564a9298db6af678b06943:
      base_file: v097.txt
      image_group_id: I1PD95942
      title: ''
      total_pages: 1198
      volume_number: 97
